### ISSUE TITLE
Can the monitoring and logging functions of multiple WAN interfaces and multiple websites be added?

### ISSUE THREAD

**Issue by openwrtdiy** [4IceG/luci-app-lite-watchdog#1]
Can the monitoring function of multiple WAN interfaces and multiple websites be added, and log details such as packet loss rate and delay status of multiple WANs within 24~48 hours can be recorded at the same time!

**Comment by 4IceG** [comment]
Hi, I'm sorry but such options will not appear in my package. I wanted the package to be maximally minimalistic and easy to configure.

I also do not remember that there was a package on OpenWrt with such possibilities, so I will not recommend anything in return.
