### ISSUE TITLE
problem with uci -q get network.wan.proto

### ISSUE THREAD

**Issue by huntz** [4IceG/luci-app-lite-watchdog#2]
Hi there,
I have installed your package on OpenWrt 22.03.5 / ZTE mf289f and the script does not work (no errors, no logs).

After some tests, I've found the problem: in the file lite_watchdog.sh, line 9, the command

> T=$(uci -q get network.wan.proto)

in my setup returns "uci: Entry not found" because I do not have an interface labelled "wan" in my setup. I have an LTE interface (labelled "LTE") that's assigned to the WAN in the firewall section.

I have fixed the script not working by modifying the line 9 as follows:

> T=$(uci -q get network.LTE.proto) 

It would be nice to be able to specify the WAN interface label via the web interface or something similar.

**Comment by 4IceG** [comment]
Hi @huntz ,
Interface can be selected in the settings, but the other thing is that the script here has wan set by default and does not take into account the user's naming imagination.

This will be fixed in the next package update.

**Comment by huntz** [comment]
Hi @4IceG,
another thing: I noticed that in Monitor->Basic Settings if I change parameters after they have been configured the first time, the cronjob is not updated in subsequent saves.
The watchdog2cron.sh script, if it sees that a watchdog cronjob already exists, does not update it.
I edited the cronjob by hand, but it would be nice to be able to do this via the web as well...

Thanks!

**Comment by 4IceG** [comment]
Hi @huntz ,
For me it is logical that I set all the parameters and only then turn on the connection monitor. I do not check the configuration afterwards to update the cron. I will add a message for user to set it this way. 

I will think about it, maybe I will also add cron updates when editing the settings.

**Comment by 4IceG** [comment]
Hi @huntz ,
The new version of the package fixes your reports.
